### ISSUE TITLE
Designing a Production-Ready Kappa Architecture for Timely Data Stream Processing / Uber

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#1]
https://eng.uber.com/kappa-architecture-data-stream-processing/

Key takeaway:
Out-of-order data is a big problem that can be mitigated but in some cases, it should be totally resolved. Usually, it resolved by using lambda architecture. Uber proposes their approach how to handle this problem in kappa architecture.

**Comment by Ceridan** [comment]
Published in [Digest #3](https://digest.deordie.org/Architecural_one/).
