### ISSUE TITLE
Change Data Capture with Flink SQL and Debezium / Marta Paes

### ISSUE THREAD

**Issue by bochkarevnv** [deordie/deordie-digest#10]
__URL:__ https://noti.st/morsapaes/liQzgs/change-data-capture-with-flink-sql-and-debezium

__Review (1-2 sentences):__ good overview of Flink, Debezium and how they can work together.

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in [Digest #3](https://digest.deordie.org/Architecural_one/).
