### ISSUE TITLE
Replicated Log / Unmesh Joshi 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#100]
__URL:__
https://martinfowler.com/articles/patterns-of-distributed-systems/replicated-log.html

__Review (1-2 sentences):__
This article helps you to understand what replication looks like. With a lot of details and a lot of code snippets, you can even write your own implementation of the replication log for sure.

**Comment by Ceridan** [comment]
Published in Digest [#19](https://digest.deordie.org/19_Back_to_business/).
