### ISSUE TITLE
Cache in distributed systems / AKT @ Medium 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#101]
__URL:__ https://medium.com/@nuraigayt/cache-in-distributed-systems-aaf92d8a05a1

__Review (1-2 sentences):__ A detailed and easy-to-understand guide to caches for 14 min read.

**Comment by Ceridan** [comment]
Published in Digest [#20](https://digest.deordie.org/20_Fantastic_Beasts_And_Where_To_Find_Them/).
