### ISSUE TITLE
Airflow Summit 2022 — The Best Of / Jarek Potiuk  

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#102]
__URL:__ https://medium.com/apache-airflow/airflow-summit-2022-the-best-of-373bee2527fa

__Review (1-2 sentences):__ A short overview of the last summit and lists of talks grouped by topic. We hope this will inspire you to watch a couple of talks.

**Comment by Ceridan** [comment]
Published in Digest [#20](https://digest.deordie.org/20_Fantastic_Beasts_And_Where_To_Find_Them/).
