### ISSUE TITLE
Towards data quality management at LinkedIn / Liangzhao Zeng @ Towards Data Science 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#103]
__URL:__ https://engineering.linkedin.com/blog/2022/towards-data-quality-management-at-linkedin

__Review (1-2 sentences):__ Short article about the top-level architecture of their Data Health Monitor system.

**Comment by Ceridan** [comment]
Published in Digest [#20](https://digest.deordie.org/20_Fantastic_Beasts_And_Where_To_Find_Them/).
