### ISSUE TITLE
Transparent memory offloading: more memory at a fraction of the cost and power / Johannes Weiner, Dan Schatzberg @ Engineering in Meta Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#104]
__URL:__ https://engineering.fb.com/2022/06/20/data-infrastructure/transparent-memory-offloading-more-memory-at-a-fraction-of-the-cost-and-power/

__Review (1-2 sentences):__  We can not say it's an actual data engineering article. But if you like deep drive to hardware,  you will appreciate

**Comment by Ceridan** [comment]
@k-tomak, could you add proper labels, please?

**Comment by k-tomak** [comment]
> @k-tomak, could you add proper labels, please?

 I'm still still thinking about if this is our topic.

**Comment by k-tomak** [comment]
I suppose it isn't our topic.
