### ISSUE TITLE
The State of Data Engineering 2022 / Einat Orr @ lakeFS Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#105]
__URL:__ https://lakefs.io/the-state-of-data-engineering-2022/

__Review (1-2 sentences):__ Let's take a look at the top technologies of 2022. Read it or you can lose the Pokémon or Big Data game :)

**Comment by Ceridan** [comment]
Published in Digest [#20](https://digest.deordie.org/20_Fantastic_Beasts_And_Where_To_Find_Them/).
