### ISSUE TITLE
Two steps towards a modern data platform / Gerben Oostra

### ISSUE THREAD

**Issue by bochkarevnv** [deordie/deordie-digest#11]
__URL:__ https://www.bigdatarepublic.nl/articles/two-steps-towards-modern-data-platform/

__Review (1-2 sentences):__ One of the views on the organization of data teams. Transformation from centralized team to data mesh

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in the [Digest #1](https://digest.deordie.org/Pilot/)
