### ISSUE TITLE
Data Quality Monitoring is dead. Say Hello to Full Data Stack Observability / Salma Bakouk 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#110]
__URL:__ https://medium.com/@salmabakouk/data-quality-monitoring-is-dead-say-hello-to-full-data-stack-observability-f73cac27ea52

__Review (1-2 sentences):__ New terms keep appearing in the world of data engineering. Today we're talking about Data Observability.

**Comment by Ceridan** [comment]
Published in Digest [#21](https://digest.deordie.org/21_Read_me_in_any_order/).
