### ISSUE TITLE
Machine Learning Operations (MLOps): Overview, Definition, and Architecture / Dominik Kreuzberger, Niklas Kühl, Sebastian Hirschl

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#112]
__URL:__ https://arxiv.org/pdf/2205.02302.pdf

__Review (1-2 sentences):__  This article comes up quite often in Twitter reposts and is definitely worth your attention. It does a very good job of systematising your knowledge of what MLOps are about and it's also easy enough to read.

**Comment by Ceridan** [comment]
Published in Digest [#21](https://digest.deordie.org/21_Read_me_in_any_order/).
