### ISSUE TITLE
Uber’s Highly Scalable and Distributed Shuffle as a Service / Mayank Bansal, Bo Yang, Mayur Bhosale, Kai Jiang @ Uber Engineering Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#113]
__URL:__ https://eng.uber.com/ubers-highly-scalable-and-distributed-shuffle-as-a-service/

__Review (1-2 sentences):__ This article is worth reading in order to dive into a new level of understanding of data shuffle in Spark.

**Comment by Ceridan** [comment]
Published in Digest [#21](https://digest.deordie.org/21_Read_me_in_any_order/).
