### ISSUE TITLE
Is DataOps the Future Of the Modern Data Stack? / The Data Downtime Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#114]
__URL:__ https://www.montecarlodata.com/blog-dataops-and-the-future-of-the-modern-data-stack/

__Review (1-2 sentences):__ Am I data engineer? Am I DataOps? What are key differences? Let's get this straight.

**Comment by Ceridan** [comment]
Published in Digest [#23](https://digest.deordie.org/23_The_Sandman_stories/).
