### ISSUE TITLE
Data + AI Summit 2022 North America/Virtual - All Sessions

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#116]
__URL:__ https://www.youtube.com/playlist?list=PLTPXxbhUt-YVWi_cf2UUDc9VZFLoRgu0l

__Review (1-2 sentences):__ 306 videos. We can't imagine how many hours of content is it. See you later)

**Comment by Ceridan** [comment]
We will include this topic as a bonus to digest 22.
