### ISSUE TITLE
Kafka Resiliency — Retry/Delay Topic, Dead Letter Queue (DLQ) / Sheshnath Kumar

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#12]
__URL:__ https://medium.com/@shesh.soft/kafka-resiliency-retry-delay-topic-dead-letter-queue-dlq-fa2434688d22

__Review (1-2 sentences):__ Three typical architectures for resilient message handling in Kafka. If you have Kafka source in your data pipelines, it can be interesting.

**Comment by Ceridan** [comment]
Published in the [Digest #2](https://digest.deordie.org/May_the_Force_be_with_you/).
