### ISSUE TITLE
Data meshes and microservices - the similarities are uncanny / Ben Morris

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#125]
__URL:__ https://www.ben-morris.com/data-meshes-and-microservices-the-similarities-are-uncanny/

__Review (1-2 sentences):__ Have you ever noticed that data teams sometimes have the same challenges as software engineering teams? So let's learn from other's mistakes.

**Comment by Ceridan** [comment]
Published in Digest [#23](https://digest.deordie.org/23_The_Sandman_stories/).
