### ISSUE TITLE
Uber Freight Carrier Metrics with Near-Real-Time Analytics / Uber Engineering Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#126]
__URL:__ https://www.uber.com/en-DE/blog/uber-freight-carrier-metrics-with-near-real-time-analytics/

__Review (1-2 sentences):__ It's time to design systems with Uber. New use case: near real time data on the Carrier App.

**Comment by Ceridan** [comment]
Published in Digest [#23](https://digest.deordie.org/23_The_Sandman_stories/).
