### ISSUE TITLE
A 2020 Reader's Guide to The Data Warehouse Toolkit / Cedric Chin @ Holistics Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#127]
__URL:__ https://www.holistics.io/blog/how-to-read-data-warehouse-toolkit/

__Review (1-2 sentences):__ Some books are out of time. Kimball is one of them. But like "War and Peace" it needs some kind of runbook on how to read it.

**Comment by Ceridan** [comment]
Published in Digest [#24](https://digest.deordie.org/24_Jack_of_all_trades/).
