### ISSUE TITLE
2 talks from Apache Kafka® Meetup

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#128]
__URL:__
https://www.youtube.com/watch?v=kJEtxWGpv3Q

__Review (1-2 sentences):__
Here are 2 talks from Apache Kafka® Meetup. 

The first one is **The Silver Bullet for Endless Rebalances** from **Confluent**. This one is highly useful to understand the theory behind rebalancing protocol and trade-offs of different implementations. Even if it's not useful for you now it is very interesting for wide auditory from a theoretical perspective. 

The second one is **Kafka as a service at Dropbox**.  Engineers from Dropbox share their experiences and problems how to provide Kafka as a service at scale.

**Comment by Ceridan** [comment]
Published in Digest [#24](https://digest.deordie.org/24_Jack_of_all_trades/).
