### ISSUE TITLE
Incremental Cooperative Rebalancing in Apache Kafka: Why Stop the World When You Can Change It?

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#129]
__URL:__
https://www.confluent.io/blog/incremental-cooperative-rebalancing-in-kafka/

__Review (1-2 sentences):__
Kafka rebalancing again ))
What is the difference between eager and incremental cooperative rebalancing protocol? What are the problems which had to implement a new one?  How is it works on high-level abstraction?

Additionally, you can go through [KIP](https://cwiki.apache.org/confluence/display/KAFKA/KIP-415%3A+Incremental+Cooperative+Rebalancing+in+Kafka+Connect) to understand the problem even deeper.

**Comment by Ceridan** [comment]
Published in Digest [#26](https://digest.deordie.org/26_Pandoras_box/).
