### ISSUE TITLE
If You’re Using Kafka With Your Microservices, You’re Probably Handling Retries Wrong / Dave Taubler

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#13]
__URL:__ https://dt-23597.medium.com/if-youre-using-kafka-with-your-microservices-you-re-probably-handling-retries-wrong-8492890899fa

__Review (1-2 sentences):__ If you deal with integration events from micro-/services as a source. Prerequisites of retry topic, typical architecture, recoverable and non-recoverable errors, ordering problems.

**Comment by Ceridan** [comment]
@k-tomak Link is not working anymore. The author has deleted the article :(
