### ISSUE TITLE
Upgrading Data Warehouse Infrastructure at Airbnb / Ronnie Zhu @ The Airbnb Tech Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#132]
__URL:__ https://medium.com/airbnb-engineering/upgrading-data-warehouse-infrastructure-at-airbnb-a4e18f09b6d5

__Review (1-2 sentences):__ Airbnb decided to refresh Spark and start using Iceberg. In this article, we will see motivation, case studies, and tuning experience.

**Comment by Ceridan** [comment]
Published in Digest [#24](https://digest.deordie.org/24_Jack_of_all_trades/).
