### ISSUE TITLE
Shopify's Playbook for Scaling Machine Learning /  Solmaz Shahalizadeh @ Shopify Engineering Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#133]
__URL:__ https://shopify.engineering/shopify-playbook-scaling-machine-learning

__Review (1-2 sentences):__  If you're at the start of building ML infrastructure and launching models it's worth reading. Good structured points about what to focus on in each period of maturity.

**Comment by Ceridan** [comment]
Published in Digest [#24](https://digest.deordie.org/24_Jack_of_all_trades/).
