### ISSUE TITLE
Git’s database internals / Derrick Stolee 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#138]
Here is a series of 5 parts that looks at Git's internals from the perspective of a database.
I have not read it, but the picture is beautiful and deserves our attention :)

- [I: Packed Object Store](https://github.blog/2022-08-29-gits-database-internals-i-packed-object-store/)
- [II: Commit History Queries](https://github.blog/2022-08-30-gits-database-internals-ii-commit-history-queries/)
- [III: File History Queries](https://github.blog/2022-08-31-gits-database-internals-iii-file-history-queries/)
- [IV: Distributed Synchronization](https://github.blog/2022-09-01-gits-database-internals-iv-distributed-synchronization/)
- [V: scalability](https://github.blog/2022-09-02-gits-database-internals-v-scalability)

**Comment by Ceridan** [comment]
Published in Digest [#26](https://digest.deordie.org/26_Pandoras_box/).
