### ISSUE TITLE
Improve federated queries with predicate pushdown in Amazon Athena / AWS Big Data Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#139]
__URL:__ https://aws.amazon.com/ru/blogs/big-data/improve-federated-queries-with-predicate-pushdown-in-amazon-athena/

__Review (1-2 sentences):__ Let's talk about query optimization in Athena, especially about predicate pushdown under different databases.

**Comment by Ceridan** [comment]
Published in Digest [#26](https://digest.deordie.org/26_Pandoras_box/).
