### ISSUE TITLE
Mussel — Airbnb’s Key-Value Store for Derived Data /  The Airbnb Tech Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#141]
__URL:__ https://medium.com/airbnb-engineering/mussel-airbnbs-key-value-store-for-derived-data-406b9fa1b296

__Review (1-2 sentences):__ It's AirBnb time to make their own database. Meet persistent, high availability and low latency key-value storage engine for accessing derived data from offline and streaming events.

**Comment by Ceridan** [comment]
Published in Digest [#26](https://digest.deordie.org/26_Pandoras_box/).
