### ISSUE TITLE
Behind the Hype: Should you ever build a Data Vault in a Lakehouse? / Advancing Analytics Channel

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#142]
__URL:__ https://www.youtube.com/watch?v=RNMoWnSWcTo&ab_channel=AdvancingAnalytics

__Review (1-2 sentences):__ The most expressive talk about Data Vault. And yes, we definitely like Simon :)

**Comment by Ceridan** [comment]
Published in Digest [#26](https://digest.deordie.org/26_Pandoras_box/).
