### ISSUE TITLE
Cost Efficiency @ Scale in Big Data File Format /  Uber Engineering blog

### ISSUE THREAD

**Issue by bochkarevnv** [deordie/deordie-digest#143]
__URL:__ https://www.uber.com/en-IE/blog/cost-efficiency-big-data/

__Review (1-2 sentences):__ If you need to choose compression type for parquet files in you data lake, this article is good starting point.

__Link to your profile (GitHub, Twitter, Facebook, etc.) for mention in digest:__

**Comment by Ceridan** [comment]
Published in Digest [#27](https://digest.deordie.org/27_New_Year_with_a_New_Database/).
