### ISSUE TITLE
Micropipelines: A Microservice Approach for DAG Authoring in Apache Airflow / Vikram Koka @ Astronomer Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#147]
__URL:__ https://www.astronomer.io/blog/micropipelines-a-microservice-approach-for-dag-authoring-in-apache-airflow/

__Review (1-2 sentences):__ No more monolithic pipelines. Please put your hands together for micropipelines!

**Comment by Ceridan** [comment]
Published in Digest [#27](https://digest.deordie.org/27_New_Year_with_a_New_Database/).
