### ISSUE TITLE
Uber’s Highly Scalable and Distributed Shuffle as a Service / Uber Blog 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#148]
__URL:__
https://www.uber.com/en-DE/blog/ubers-highly-scalable-and-distributed-shuffle-as-a-service/

__Review (1-2 sentences):__ As usual, Uber tries to move the industry forward by resolving their scalability and reliability problems. In this article, they describe their way to move away from a built-in spark shuffle to a more costless and reliable way by using streaming writing. They built a library for this purpose and published it to open-source. So a lot of materials to explore.

**Comment by k-tomak** [comment]
Copy of #113 (published in Digest 21)

**Comment by DashaBulanova** [comment]
Ops.... sorry (
