### ISSUE TITLE
Why your mock doesn’t work / Ned Batchelder 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#149]
__URL:__
https://nedbatchelder.com/blog/201908/why_your_mock_doesnt_work.html

__Review (1-2 sentences):__ I have often come across situations where my Mock didn't work as I expected. I always hated python language for that. This pretty short article showed me that I should have hated someone else [most likely underinvestment into languate]. I just misunderstood the basics. If you like me this is a must-read article. It has a brief explanation of how exactly variable assignment in import statements works in python and what we should keep in mind working with Mock.

**Comment by Ceridan** [comment]
Published in Digest [#28](https://digest.deordie.org/28_No_data_—_no_problem/).
