### ISSUE TITLE
Composable Data Processing with Apache Spark / Data & AI Summit 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#15]
__URL:__ https://databricks.com/session_na20/composable-data-processing-with-apache-spark

__Review (1-2 sentences):__  Use it for single data pipeline architecture ideas. Data parsing, validation,  quarantining. Much attention is paid to error handling. With great examples.

**Comment by Ceridan** [comment]
Published in [Digest #3](https://digest.deordie.org/Architecural_one/).
