### ISSUE TITLE
Learn to Efficiently Test ETL Pipelines / Jacqueline Bilston 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#150]
__URL:__
https://www.youtube.com/watch?v=uzVewG8M6r0

__Review (1-2 sentences):__ This is an absolutely amazing presentation about unit testing data pipelines. Hadn’t seen any resource that was so specific about data pipeline testing so far.

**Comment by Ceridan** [comment]
Published in Digest [#27](https://digest.deordie.org/27_New_Year_with_a_New_Database/).
