### ISSUE TITLE
Asynchronous computing at Meta: Overview and learnings / Engineering at Meta Blog 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#151]
__URL:__
https://engineering.fb.com/2020/08/17/production-engineering/async/
https://engineering.fb.com/2023/01/31/production-engineering/meta-asynchronous-computing/

__Review (1-2 sentences):__
By the name you could think that is something from other world. And you will right. But only partially. Actually this is 2 articles of how to build a mix of scalable ETL and distributed computation in-house.

**Comment by Ceridan** [comment]
Published in Digest [#28](https://digest.deordie.org/28_No_data_—_no_problem/).
