### ISSUE TITLE
Title: 5 Ways to Use Column Level Data Lineage / Montecarlo Data Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#152]
__URL:__ https://www.montecarlodata.com/title-5-ways-to-use-column-level-data-lineage/?utm_source=rss&utm_medium=rss&utm_campaign=title-5-ways-to-use-column-level-data-lineage

__Review (1-2 sentences):__ Have you ever thought of implementing column level lineage? If not, just read why it can be extremely helpful to have.

**Comment by Ceridan** [comment]
Published in Digest [#28](https://digest.deordie.org/28_No_data_—_no_problem/).
