### ISSUE TITLE
Solving Advent of Code with DuckDB and DBT / Graham  Wetzler

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#154]
__URL:__ https://motherduck.com/blog/solving-advent-code-duckdb-dbt/

__Review (1-2 sentences):__ Have you ever thought about solving Advent of Code using SQL? While ones dream others do.

**Comment by Ceridan** [comment]
Published in Digest [#29](https://digest.deordie.org/29_Advent_of_Data/).
