### ISSUE TITLE
Distinct aggregation optimization in Apache Calcite and Trino / Querify Labs Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#155]
__URL:__ https://www.querifylabs.com/blog/distinct-aggregation-optimization-in-apache-calcite-and-trino

__Review (1-2 sentences):__ Good and detailed description of how DISTINCT is implemented in Calcite and Trino engines.

**Comment by Ceridan** [comment]
Published in Digest [#29](https://digest.deordie.org/29_Advent_of_Data/).
