### ISSUE TITLE
The Chaos Data-Engineering Manifesto / Shane Murray @ Towards Data Science Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#156]
__URL:__ https://towardsdatascience.com/the-chaos-data-engineering-manifesto-5dc09a182e85

__Review (1-2 sentences):__  Very vital and easy-to-read article about the adaptation of chaos engineering to meet the needs of data engineers. "Nothing acts like prod, but prod." And nothing fails like prod, but prod.

**Comment by Ceridan** [comment]
Published in Digest [#29](https://digest.deordie.org/29_Advent_of_Data/).
