### ISSUE TITLE
Essential Snowflake Cost Reduction Strategies / Niall Woodward @ select.dev Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#157]
__URL:__ https://select.dev/posts/essential-snowflake-cost-reduction-strategies

__Review (1-2 sentences):__  Cloud can help you to release MVP as soon as possible. But also in final you can be bare as a bone. How to prevent it?

**Comment by Ceridan** [comment]
Published in Digest [#29](https://digest.deordie.org/29_Advent_of_Data/).
