### ISSUE TITLE
The Data Engineer’s Roadmap / James Phoenix 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#158]
__URL:__ https://understandingdata.com/posts/the-data-engineers-roadmap/

__Review (1-2 sentences):__ You will say: "Oh, another one article about how to be a data engineer." But! Firstly, there are new data engineers who want to grow. Secondly, we have team leads here so that they can share this article with colleagues. Additional materials included <3

**Comment by Ceridan** [comment]
Published in Digest [#29](https://digest.deordie.org/29_Advent_of_Data/).
