### ISSUE TITLE
Concurrency is not Parallelism by Rob Pike

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#159]
__URL:__
https://www.youtube.com/watch?v=oV9rvDllKEg

__Review (1-2 sentences):__
Rob Pike is a software engineer, best known for his work on the Go programming language. This is his excellent talk discussing the crucial distinctions between concurrency and parallelism. Such foundational engineering concepts are cross disciplines and I would say must-have knowledge for all engineers.

Additionally, **red jacket** is fire!

**Comment by Ceridan** [comment]
Published in Digest [#30](https://digest.deordie.org/30_Go_to_Data_Engineering/).
