### ISSUE TITLE
Keystone Real-time Stream Processing Platform / Netflix Technology Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#16]
__URL:__ https://netflixtechblog.com/keystone-real-time-stream-processing-platform-a3ee651812a

__Review (1-2 sentences):__ High-level overview of Netflix design principles and approaches.

**Comment by Ceridan** [comment]
Published in [Digest #4](https://digest.deordie.org/04_A_spark_of_the_summer_sun/).
