### ISSUE TITLE
Setting Uber’s Transactional Data Lake in Motion with Incremental ETL Using Apache Hudi / Uber 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#160]
__URL:__
https://www.uber.com/en-DE/blog/ubers-lakehouse-architecture/

__Review (1-2 sentences):__
As usual, Uber's blog is fantastic resource for new ideas. This fresh article explains how to build streaming ETL framework and how to address some well-known issue on this way.

**Comment by Ceridan** [comment]
Published in Digest [#30](https://digest.deordie.org/30_Go_to_Data_Engineering/).
