### ISSUE TITLE
Apache Spark — Job monitoring / Hareesha Dandamudi 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#161]
__URL:__ https://medium.com/@hareesha1906/apache-spark-job-monitoring-f2332ef50915

__Review (1-2 sentences):__ Short and understandable article about SparkListener. Quite a useful thing for creating monitoring and lineage handling (as OpenLineage does). Just use it as a start for your own articles research :)

**Comment by Ceridan** [comment]
Published in Digest [#30](https://digest.deordie.org/30_Go_to_Data_Engineering/).
