### ISSUE TITLE
The Question That Every Data Engineer Should Ask / Xinran Waibel @ Data Engineer Things Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#162]
__URL:__ https://medium.com/data-engineer-things/the-question-that-every-data-engineer-should-ask-a70cb6d422e4

__Review (1-2 sentences):__ Vital and clickbait.

**Comment by Ceridan** [comment]
Published in Digest [#30](https://digest.deordie.org/30_Go_to_Data_Engineering/).
