### ISSUE TITLE
Pushdown / Trino Query optimizer docs 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#163]
__URL:__ https://trino.io/docs/current/optimizer/pushdown.html

__Review (1-2 sentences):__ Pushdown is a powerful query optimization that moves predicates in the WHERE clause closer to the tables they refer to. This is Trino docs, but you can go through all types and find them in other query engines. It can help you in reading query plans a lot.

**Comment by Ceridan** [comment]
Published in Digest [#30](https://digest.deordie.org/30_Go_to_Data_Engineering/).
