### ISSUE TITLE
Introducing Entity-Centric Data Modeling for Analytics / Maxime Beauchemin @ Preset Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#164]
__URL:__ https://preset.io/blog/introducing-entity-centric-data-modeling-for-analytics/

__Review (1-2 sentences):__  Entity-centric data modeling (ECM) introduction from Maxime Beauchemin, CEO Preset and creator and lead committer on Apache Airflow and Apache Superset. Just imagine that metrics can also live in the dimension tables and go to read.

**Comment by Ceridan** [comment]
Published in Digest [#31](https://digest.deordie.org/31_Data-driven_is_a_new_black/).
