### ISSUE TITLE
Software Architecture and Design InfoQ Trends Report - April 2023 / InfoQ

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#165]
__URL:__ https://www.infoq.com/articles/architecture-trends-2023/

__Review (1-2 sentences):__ Data engineers are dealing with code as much as with data. It means that software architecture and design are not alien to us.

**Comment by Ceridan** [comment]
Published in Digest [#31](https://digest.deordie.org/31_Data-driven_is_a_new_black/).
