### ISSUE TITLE
The end of a myth: Distributed transactions can scale / Murat Demirbas Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#166]
__URL:__ http://muratbuffalo.blogspot.com/2023/04/the-end-of-myth-distributed.html

__Review (1-2 sentences):__ Analysis of the article of the same name. If you want to switch your mind, then remote direct memory access and snapshot isolation are waiting for you.

**Comment by Ceridan** [comment]
Published in Digest [#31](https://digest.deordie.org/31_Data-driven_is_a_new_black/).
