### ISSUE TITLE
Functional Data Engineering — a modern paradigm for batch data processing / Maxime Beauchemin 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#168]
__URL:__ https://maximebeauchemin.medium.com/functional-data-engineering-a-modern-paradigm-for-batch-data-processing-2327ec32c42a

__Review (1-2 sentences):__ It's very old. But quite conceptual.

**Comment by Ceridan** [comment]
Published in Digest [#32](https://digest.deordie.org/32_Follow_the_Spark/).
