### ISSUE TITLE
Your Data Catalog Shouldn’t Be Just One More UI / Mahdi Karabiben 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#169]
__URL:__ https://towardsdatascience.com/your-data-catalog-shouldnt-be-just-one-more-ui-e6bffb793cf1

__Review (1-2 sentences):__ When data catalog is not only for business users.

**Comment by Ceridan** [comment]
Published in Digest [#31](https://digest.deordie.org/31_Data-driven_is_a_new_black/).
