### ISSUE TITLE
Byte Down: Making Netflix’s Data Infrastructure Cost-Effective / Netflix 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#17]
__URL:__
https://netflixtechblog.com/byte-down-making-netflixs-data-infrastructure-cost-effective-fee7b3235032

__Review (1-2 sentences):__
Some useful ideas of categorizing your infrastructure cost and what can help keep it under control.

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in the [Digest #2](https://digest.deordie.org/May_the_Force_be_with_you/).
