### ISSUE TITLE
Spark SQL Query Engine Deep Dive Parts I and II – Adaptive Query Execution / Linxiao Ma 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#171]
__URL:__ https://dataninjago.com/2022/02/14/spark-sql-query-engine-deep-dive-19-adaptive-query-execution-part-1/ &
https://dataninjago.com/2022/02/21/spark-sql-query-engine-deep-dive-20-adaptive-query-execution-part-2/

__Review (1-2 sentences):__  It's absolutely brilliant blog. I adore it. These articles declares Spark Adaptive Query Execution very deeply.

**Comment by Ceridan** [comment]
Published in Digest [#32](https://digest.deordie.org/32_Follow_the_Spark/).
