### ISSUE TITLE
Spark Connect Available in Apache Spark 3.4 / Databricks Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#172]
__URL:__ https://www.databricks.com/blog/2023/04/18/spark-connect-available-apache-spark.html

__Review (1-2 sentences):__ Just to keep in touch with a new Spark features. Give it up for Spark Connect.

**Comment by Ceridan** [comment]
Published in Digest [#32](https://digest.deordie.org/32_Follow_the_Spark/).
