### ISSUE TITLE
5 Helpful Extract & Load Practices for High-Quality Raw Data / Sven Balnojan 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#173]
__URL:__ https://towardsdatascience.com/5-helpful-extract-load-practices-for-high-quality-raw-data-65b9a59a8721

__Review (1-2 sentences):__ What layer do you focus on when creating data architecture? If it's not Raw, then this article is for you. 5 points that will save your time n future.

**Comment by Ceridan** [comment]
Published in Digest [#32](https://digest.deordie.org/32_Follow_the_Spark/).
