### ISSUE TITLE
The State of Data Engineering 2023 / Einat Orr @ lakeFS blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#177]
__URL:__ https://lakefs.io/blog/the-state-of-data-engineering-2023/#h-observability

__Review (1-2 sentences):__ It's time to reveal new State of Data Engineering with lakeFS!

**Comment by Ceridan** [comment]
Published in Digest [#33](https://digest.deordie.org/33_Thoughts_on_privacy_and_privacy_of_thoughts/).
