### ISSUE TITLE
Dynamic Filtering: a Critical Performance Optimization in Analytical Engines / Vladimir Ozerov @ Querify Labs Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#178]
__URL:__ https://www.querifylabs.com/blog/dynamic-filtering-in-analytical-engines

__Review (1-2 sentences):__ Let's continue getting acquainted with the query engine optimization techniques with developers of these query engines. Now it's dynamic filtering time.

**Comment by Ceridan** [comment]
Published in Digest [#33](https://digest.deordie.org/33_Thoughts_on_privacy_and_privacy_of_thoughts/).
