### ISSUE TITLE
RocksDB + Flink

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#18]
__URL:__  https://www.ververica.com/blog/manage-rocksdb-memory-size-apache-flink
__Review (1-2 sentences):__ Flink may be the next big hype thing. RocksDB is already a hype. And it's not a secret at all that they're connected, but here is the tricky part: how to manage RocksDB size? This post describes three configurations which you may need to manage it.

**Comment by bochkarevnv** [comment]
@asm0dey there is no link

**Comment by asm0dey** [comment]
At least somebody is reading, thanks @bochkarevnv  :)

**Comment by Ceridan** [comment]
Too late to pubish :)
