### ISSUE TITLE
Is Kimball Still Relevant? / Joe Reis Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#181]
__URL:__ https://joereis.substack.com/p/is-kimball-still-relevant

__Review (1-2 sentences):__ Quite a vital question :D Also, some links inside this post also have vital questions. If you're thinking of dropping a detailed layer on DWH, you can read it.

**Comment by Ceridan** [comment]
Published in Digest [#34](https://digest.deordie.org/34_Score_your_data_zoo/).
