### ISSUE TITLE
Seven Principles of Cloud-Native Architecture/ Alibaba Cloud Native Community Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#186]
__URL:__ https://www.alibabacloud.com/blog/seven-principles-of-cloud-native-architecture_598431

__Review (1-2 sentences):__ Good and clear explanation of cloud-native architecture principles.

**Comment by Ceridan** [comment]
Published in Digest [#34](https://digest.deordie.org/34_Score_your_data_zoo/).
