### ISSUE TITLE
Streaming SQL in Data Mesh / Netflix Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#188]
__URL:__ https://netflixtechblog.com/streaming-sql-in-data-mesh-0d83f5a00d08

__Review (1-2 sentences):__ May be, if you're writing a Data Platform in your company, there are not too many insights here. But I guarantee at least one: look how UI for Data Platform can look like

**Comment by Ceridan** [comment]
Published in Digest [#34](https://digest.deordie.org/34_Score_your_data_zoo/).
