### ISSUE TITLE
Data Quality Score: The next chapter of data quality at Airbnb / Airbnb blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#189]
__URL:__ https://medium.com/airbnb-engineering/data-quality-score-the-next-chapter-of-data-quality-at-airbnb-851dccda19c3

__Review (1-2 sentences):__ Absolutely clear and brilliant approach of identifying data quality for all company data assets. And quite realistic approach.

**Comment by Ceridan** [comment]
Published in Digest [#34](https://digest.deordie.org/34_Score_your_data_zoo/).
