### ISSUE TITLE
Creating Pandas and Spark Compatible Functions with Fugue

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#19]
__URL:__ https://towardsdatascience.com/creating-pandas-and-spark-compatible-functions-with-fugue-8617c0b3d3a8

__Review (1-2 sentences):__ Everybody knows about Apache Arrow, which aims to create effective in-memory storage format for interaction of different libraries/frameworks. But what if there were such universal format not for storage, but for functions? There is one: Fugue

**Comment by Ceridan** [comment]
Published in [Digest #4](https://digest.deordie.org/04_A_spark_of_the_summer_sun/).
