### ISSUE TITLE
Data Domains — Where do I start? / Piethein Strengholt 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#197]
__URL:__ https://towardsdatascience.com/data-domains-where-do-i-start-a6d52fef95d1

__Review (1-2 sentences):__ Good and practical article about data domains. Not only from a data team perspective but also from a development perspective.

**Comment by Ceridan** [comment]
Published in Digest [#35](https://digest.deordie.org/35_Get_your_data_just-in-time/).
