### ISSUE TITLE
Data Quality Score: How We Evolved the Data Quality Strategy at Airbnb / Clark Wright @ Netflix Data Engineering Open Forum 2024 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#199]
__URL:__ https://youtu.be/Lv-bFDSzrqw?si=7ie3Nj4YXfyvCEDn

__Review (1-2 sentences):__ [Some time ago](https://digest.deordie.org/34_Score_your_data_zoo/), we published an article from AirBnb about the Data Quality framework that they had built. Now, you may watch the video for more details. Inspired by the level of platform solutions that they're building.

**Comment by Ceridan** [comment]
Published in Digest [#36](https://digest.deordie.org/36_A_few_moments_later/).
