### ISSUE TITLE
Handling Late Arriving Dimensions Using a Reconciliation Pattern /  McGraw Hill Education

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#2]
__URL:__
https://databricks.com/blog/2020/12/15/handling-late-arriving-dimensions-using-a-reconciliation-pattern.html

__Review (1-2 sentences):__

Several approaches to how to handle late-arriving dimensions. Its problems and evolution from the first idea.
No soo is deep as would like but the core ideas are understandable.
_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in the [Digest #1](https://digest.deordie.org/Pilot/)
