### ISSUE TITLE
Replace Kafka with DB

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#20]
__URL:__ https://towardsdatascience.com/you-can-replace-kafka-with-a-database-39e13b610b63

__Review (1-2 sentences):__ Kafka is he new gold. What if you don't like it and want to replace it? Of course there are options like Apache Pulsar, but… is it possible to replace Apache Kafka with relational DB? Looks like the answer is "yes". Now it's yout turn to decide if you need it :)

**Comment by k-tomak** [comment]
Паш, блог платный
но тема интересная.
как думаешь, можно найти похожую
например, эту
https://www.kai-waehner.de/blog/2020/03/12/can-apache-kafka-replace-database-acid-storage-transactions-sql-nosql-data-lake/
или вот. интересная но такая..сложная для чтения именно
https://dzone.com/articles/is-apache-kafka-a-database-the-2020-update

**Comment by asm0dey** [comment]
А он прям платный или там ограниченное количество просмотров в месяц?

**Comment by k-tomak** [comment]
3 в месяц

**Comment by Ceridan** [comment]
Please, let keep the conversation in English. We pretend to be an international resource.

**Comment by Ceridan** [comment]
Published in [Digest #3](https://digest.deordie.org/Architecural_one/).
