### ISSUE TITLE
Course Events and Event Streaming / Adam Bellemare @ Confluent Developer

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#201]
__URL:__ https://developer.confluent.io/courses/event-design/intro/

__Review (1-2 sentences):__ If you, as a data engineer, have discussions about proper event modeling in your company, then this video course is for you (and for your software engineers).

**Comment by Ceridan** [comment]
Published in Digest [#36](https://digest.deordie.org/36_A_few_moments_later/).
