### ISSUE TITLE
InfoQ Software Architecture and Design Trends Report - April 2024 / InfoQ 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#202]
__URL:__ https://www.infoq.com/articles/architecture-trends-2024

__Review (1-2 sentences):__ Have you already heard about architecture as a team sport? About cell-based architecture? Review the latest innovations and trends in the design trends report ;)

**Comment by Ceridan** [comment]
Published in Digest [#36](https://digest.deordie.org/36_A_few_moments_later/).
