### ISSUE TITLE
Distributed computing for neuroimaging

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#21]
__URL:__ https://towardsdatascience.com/using-distributed-computing-for-neuroimaging-2689cfc144c9?gi=701ac393075d

__Review (1-2 sentences):__ Did you ever think that data engineering may literally save lifes? Well, turns out it can.

**Comment by Ceridan** [comment]
Published in [Digest #4](https://digest.deordie.org/04_A_spark_of_the_summer_sun/).
