### ISSUE TITLE
Evolution to the Data Lakehouse / Bill Inmon, Mary Levins at Databricks blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#22]
__URL:__
https://databricks.com/blog/2021/05/19/evolution-to-the-data-lakehouse.html

__Review (1-2 sentences):__
The history of the evolution of data warehouses into data lakes and further into data lakehouses. Pros and cons of these approaches.

**Comment by Ceridan** [comment]
Published in [Digest #3](https://digest.deordie.org/Architecural_one/).
