### ISSUE TITLE
How to Move Beyond a Monolithic Data Lake to a Distributed Data Mesh

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#23]
__URL:__ https://martinfowler.com/articles/data-monolith-to-mesh.html

__Review (1-2 sentences):__ Huge post on potential architecture of enterprise data store. Current options and pattern, what should we think about and what challenges we will face.

**Comment by Ceridan** [comment]
Published in [Digest #4](https://digest.deordie.org/04_A_spark_of_the_summer_sun/).
