### ISSUE TITLE
4 Layers of a Modern Data Pipeline

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#24]
__URL:__ https://thomaskane.io/4-layers-of-a-modern-data-pipeline

__Review (1-2 sentences):__ It's a short, but comprehensive post, which describes author's take on how modern pipelines are built and what they consist of

**Comment by Ceridan** [comment]
Published in Digest [#7](https://digest.deordie.org/07_Late_arriving_digest/).
