### ISSUE TITLE
Uber’s Data Journey 100+PB with Minute Latency / Uber 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#25]
__URL:__
https://youtu.be/YxlmgwHJaqw

__Review (1-2 sentences):__
In this talk Uber reflects on their journey with scaling Data Infrastructure from 1PB to 10PB to 100PB and beyond while reducing latency from 24 hours to 3h to 1h to 10 minutes. There a lot of details about architecture evolution and instruments. And one important point at what point should you think about building Data Platform.

**Comment by k-tomak** [comment]
Comment
Uber talk about three generations of data systems, their architecture, pains, limitations, insights. We like to watch about typical architectures so why not look at three at once.

**Comment by Ceridan** [comment]
Published in [Digest #4](https://digest.deordie.org/04_A_spark_of_the_summer_sun/).
