### ISSUE TITLE
Event-time Aggregation and Watermarking in Apache Spark’s Structured Streaming / Databricks 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#26]
__URL:__
https://databricks.com/blog/2017/05/08/event-time-aggregation-watermarking-apache-sparks-structured-streaming.html

__Review (1-2 sentences):__
If you use Spark Streaming and you are interested in how to handle late-arriving data this article gives you a practical approach to which windows strategy use and how watermark can help you.

**Comment by Ceridan** [comment]
Published in Digest [#5](https://digest.deordie.org/05_Big_data_with_a_toy_database/).
