### ISSUE TITLE
A Visual Introduction to Debezium / Dunith Dhanushka at @Medium 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#28]
__URL:__ https://medium.com/event-driven-utopia/a-visual-introduction-to-debezium-32563e23c6b8

__Review (1-2 sentences):__ If you are not using Debezium yet but really want to start to do it, read this article or just look at the pictures :)

**Comment by Ceridan** [comment]
Published in Digest [#5](https://digest.deordie.org/05_Big_data_with_a_toy_database/).
