### ISSUE TITLE
Error Handling Patterns for Apache Kafka Applications / Gerardo Villeda at @Confluent Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#29]
__URL:__ https://www.confluent.io/blog/error-handling-patterns-in-kafka/

__Review (1-2 sentences):__ Great article about typical approaches to handling error messages in Kafka. With our favorite confluent pictures!

**Comment by Ceridan** [comment]
Published in Digest [#5](https://digest.deordie.org/05_Big_data_with_a_toy_database/).
