### ISSUE TITLE
Uber’s Journey Toward Better Data Culture From First Principles / Uber 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#3]
__URL:__
https://eng.uber.com/ubers-journey-toward-better-data-culture-from-first-principles/

__Review (1-2 sentences):__
I lot of appliable ideas on how processes around data at scale can look like, areas of responsibility, and metrics of quality.

**Comment by Ceridan** [comment]
Published in the [Digest #1](https://digest.deordie.org/Pilot/)
