### ISSUE TITLE
Data quality roadmap by Wrike

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#30]
__URL:__

https://medium.com/wriketechclub/data-quality-roadmap-part-i-61332d5be7a
https://medium.com/wriketechclub/data-quality-roadmap-part-ii-case-studies-614e85906178

__Review (1-2 sentences):__

Contrary to what we used to do — just building tests and metering time, folks from Wrike are creating the comprehensive matrix of what data quality is, how to achieve this quality and how to measure it. More than that, they're discussing what could go wrong without these metrics! (Anything, of course)

**Comment by k-tomak** [comment]
brilliant!

**Comment by Ceridan** [comment]
Published in Digest [#5](https://digest.deordie.org/05_Big_data_with_a_toy_database/).
