### ISSUE TITLE
Adopting Dagster at Mapbox

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#31]
__URL:__ https://medium.com/dagster-io/incrementally-adopting-dagster-at-mapbox-b635b1118594

__Review (1-2 sentences):__ We all know that Dagster may be (and maybe already is) the Next Big Thing after Airflow. But how many success stories did you read? Yes, adoption grows, but something impossible with Airflow? Well, folks from Mapbox hit the wall of complexity with Airflow and Dagster is what saved them (they think)

**Comment by Ceridan** [comment]
Published in Digest [#6](https://digest.deordie.org/06_Pipeline_vibes/).
