### ISSUE TITLE
Google Data Fusion

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#32]
__URL:__ https://towardsdatascience.com/data-fusion-a-code-free-pipeline-for-your-google-cloud-data-warehouse-5b31dd4be91e

__Review (1-2 sentences):__ everybody loves to get results without writing a code. The most popular solution for building pipelines without code is Apache NiFi. But what if one can build the whole warehouse with all processes inside without code? Looks like Google Data Fusion may be used for it!

**Comment by Ceridan** [comment]
Published in Digest [#6](https://digest.deordie.org/06_Pipeline_vibes/).
