### ISSUE TITLE
Data Quality Meetup / Gleb Mezhanskiy 

### ISSUE THREAD

**Issue by SimonOsipov** [deordie/deordie-digest#33]
__URL:__
https://www.datafold.com/blog/data-quality-meetup-4/

__Review (1-2 sentences):__
Data Quality Meetup from DataFold. Next topics discussed: 
- [The Best Data Quality Investment in 2021](https://www.datafold.com/blog/data-quality-meetup-4/#the-best-data-quality-investment-in-2021)
- [Verity: Data Quality as a Service](https://www.datafold.com/blog/data-quality-meetup-4/#verity-data-quality-as-a-service)
- [Unit Tests for SQL with dbt & Python](https://www.datafold.com/blog/data-quality-meetup-4/#unit-tests-for-sql-with-dbt-python)
- [Building Security Conscious Data Apps](https://www.datafold.com/blog/data-quality-meetup-4/#building-security-conscious-data-apps)
- [Fake It Till You Make It: A Backward Approach to Data Products](https://www.datafold.com/blog/data-quality-meetup-4/#fake-it-till-you-make-it-a-backward-approach-to-data-products)

**Comment by Ceridan** [comment]
Published in Digest [#6](https://digest.deordie.org/06_Pipeline_vibes/).
