### ISSUE TITLE
Understanding Kafka Topic Partitions / Dunith Dhanushka 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#34]
__URL:__ https://medium.com/event-driven-utopia/understanding-kafka-topic-partitions-ae40f80552e8

__Review (1-2 sentences):__ I'm a Dunith Dhanushka articles fan: many schemes, easy to read, practical use!

**Comment by Ceridan** [comment]
Published in Digest [#6](https://digest.deordie.org/06_Pipeline_vibes/).
