### ISSUE TITLE
How we deal with Data Quality using Circuit Breakers / Intuit 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#35]
__URL:__
https://medium.com/wrong-ml/taming-data-quality-with-circuit-breakers-dbe550d3ca78

__Review (1-2 sentences):__
This is an interesting way as guys use circuit breaker pattern inside the pipeline processes to prevent low-quality data from propagating to downstream processes.

**Comment by Ceridan** [comment]
Published in Digest [#7](https://digest.deordie.org/07_Late_arriving_digest/).
