### ISSUE TITLE
Apache Kafka Rebalance Protocol, or the magic behind your streams applications / Stream Thoughts

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#36]
__URL:__
https://medium.com/streamthoughts/apache-kafka-rebalance-protocol-or-the-magic-behind-your-streams-applications-e94baf68e4f2

__Review (1-2 sentences):__
If you would like to know a little bit deeper about the foundation of the Apache Kafka consumption mechanism this is a very good article for this. Personally, I didn't understand clearly tons of "rebalancing" log entries till reading this article.

**Comment by Ceridan** [comment]
Published in Digest [#7](https://digest.deordie.org/07_Late_arriving_digest/).
