### ISSUE TITLE
Link parsing in Digest

### ISSUE THREAD

**Issue by SimonOsipov** [deordie/deordie-digest#37]
![CleanShot 2021-07-06 at 10 53 34](https://user-images.githubusercontent.com/28685772/124563424-b2943100-de48-11eb-8dd1-a8c1f6eee58f.png)
It seems like links to GitHub not parsed (or not inserted). 

Suggestion:
- add GitHub link
- ask the author of the suggested topic to add his Twitter/FB/GH to be mentioned in the issue template

**Comment by SimonOsipov** [comment]
Can you take a look, @asm0dey?

**Comment by Ceridan** [comment]
Yep, it doesn't suppose to work for now. What link do you prefer for your mention?

**Comment by SimonOsipov** [comment]
There is a suggestion in my original post

- add GitHub link by default
- ask the author of the suggested topic to add his Twitter/FB/GH to be mentioned in the issue template

For this particular case I would like to be my Twitter mentioned (https://twitter.com/OsipovSimon)

**Comment by Ceridan** [comment]
Thank you for the suggestion. I update the issue template with a link to profile section. Also, I added link to your Twitter profile in the latest digest.
