### ISSUE TITLE
Design a data mesh architecture using AWS Lake Formation and AWS Glue / AWS Big Data Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#38]
__URL:__ https://aws.amazon.com/blogs/big-data/design-a-data-mesh-architecture-using-aws-lake-formation-and-aws-glue/

__Review (1-2 sentences):__ What is data mesh? How to do it? An AWS implementation of data architecture for data mesh.

**Comment by Ceridan** [comment]
Published in Digest [#7](https://digest.deordie.org/07_Late_arriving_digest/).
