### ISSUE TITLE
Data Lake vs. Data Warehouse / Subsurface Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#39]
__URL:__ https://www.dremio.com/subsurface/data-lake-vs-data-warehouse/

__Review (1-2 sentences):__ If you're new in data engineering, this article'll provide an opportunity to synchronize terminology and understanding of key concepts and its differences. Without further ado, just the essence.

**Comment by Ceridan** [comment]
Published in Digest [#8](https://digest.deordie.org/08_4_things_and_5_more_reasons/).
