### ISSUE TITLE
Visualizing Data Timeliness at Airbnb / Airbnb 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#4]
__URL:__
https://medium.com/airbnb-engineering/visualizing-data-timeliness-at-airbnb-ee638fdf4710

__Review (1-2 sentences):__
I think you should open this article only for viewing perfect UI and feeling a professional approach to building tools. Also, you can learn how to segregate different areas. I hope Airbnb will open this perfect tool in the near future.

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in the [Digest #1](https://digest.deordie.org/Pilot/)
