### ISSUE TITLE
Containerizing Apache Hadoop Infrastructure at Uber / Uber Engineering Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#40]
__URL:__ https://eng.uber.com/hadoop-container-blog/

__Review (1-2 sentences):__ Detailed technical article about re-architecting the Uber's Hadoop deployment stack for 21000+ hosts. Cluster management, docker containers, configs and many more.

**Comment by Ceridan** [comment]
Published in Digest [#9](https://digest.deordie.org/09_Goddess_blessing/).
