### ISSUE TITLE
How Airbnb Achieved Metric Consistency at Scale / Robert Chang @  The Airbnb Tech Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#41]
__URL:__  Part I https://medium.com/airbnb-engineering/how-airbnb-achieved-metric-consistency-at-scale-f23cc53dea70
Part II https://medium.com/airbnb-engineering/airbnb-metric-computation-with-minerva-part-2-9afe6695b486

__Review (1-2 sentences):__ Do you have data marts in your DWH? Did you ever face with problem of data marts duplication?  How to avoid garbage in Data Marts layer? How to build clear single source of truth for business metrics? Let's read about Minerva — Airbnb’s metric platform. ALL STUNTS WERE PERFORMED IN CONTROLLED ENVIRONMENTS WITH PROFESSIONALLY TRAINED STUNT CREWS ON CLOSED ROADS.

**Comment by Ceridan** [comment]
Published in Digest [#9](https://digest.deordie.org/09_Goddess_blessing/).
