### ISSUE TITLE
4 Things You Need to Know When Solving for Data Quality / Barr Moses @ Towards Data Science Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#42]
__URL:__. https://towardsdatascience.com/4-things-you-need-to-know-when-solving-for-data-quality-4abf6d31b2c9

__Review (1-2 sentences):__ Barr Moses is a professional in making data reliable. There are key 4 points that will give you back a healthy pragmatism.  Definitely recommend to read.

**Comment by Ceridan** [comment]
Published in Digest [#8](https://digest.deordie.org/08_4_things_and_5_more_reasons/).
