### ISSUE TITLE
Create Cloud Architecture with Diagrams for AWS, Azure, and GPC / Bruce H. Cottman 

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#43]
__URL:__ https://towardsdatascience.com/create-cloud-architecture-with-diagrams-for-aws-azure-and-gpc-8fb528f6c6cf
https://kroki.io/

__Review (1-2 sentences):__ Sometimes we all need to project our cloud reality to paper. Did you know that you can do it with text?

__Link to your profile (GitHub, Twitter, Facebook, etc.) for mention in digest:__

**Comment by Ceridan** [comment]
Published in Digest [#8](https://digest.deordie.org/08_4_things_and_5_more_reasons/).
