### ISSUE TITLE
Benchmarking of simple DB operations / H2O 

### ISSUE THREAD

**Issue by SimonOsipov** [deordie/deordie-digest#44]
__URL:__
https://h2oai.github.io/db-benchmark/

__Review (1-2 sentences):__
Benchmark of several DB on simple operations on a various amounts of data.

__Link to your profile (GitHub, Twitter, Facebook, etc.) for mention in the digest:__
Twitter [SimonOsipov](https://twitter.com/OsipovSimon)

**Comment by Ceridan** [comment]
Published in Digest [#9](https://digest.deordie.org/09_Goddess_blessing/).
