### ISSUE TITLE
5 More Reasons to Choose Apache Pulsar Over Apache Kafka / Chris Bartholomew @ DataStax Blog at Medium 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#45]
__URL:__ https://medium.com/building-the-open-data-stack/5-more-reasons-to-choose-apache-pulsar-over-apache-kafka-c09b259e3691

__Review (1-2 sentences):__ Do you like platform comparisons? I've read almost nothing about Apache Pulsar. But after point about tiered storage in Pulsar, when you can move old messages to cheaper storage to store it always, I was inspired.

**Comment by Ceridan** [comment]
Published in Digest [#8](https://digest.deordie.org/08_4_things_and_5_more_reasons/).
