### ISSUE TITLE
Data Movement in Netflix Studio via Data Mesh / Netflix Technology Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#46]
__URL:__ https://netflixtechblog.com/data-movement-in-netflix-studio-via-data-mesh-3fddcceb1059

__Review (1-2 sentences):__ New interesting article about Netflix platform. How to combine not quite that Data Mesh, CDC, schema evolution, data enrichment and data quality? Read the article.

**Comment by Ceridan** [comment]
Published in Digest [#9](https://digest.deordie.org/09_Goddess_blessing/).
