### ISSUE TITLE
Migrating to Apache Iceberg at Adobe Experience Platform /  Jaemi Bremner 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#47]
__URL:__ https://medium.com/adobetech/migrating-to-apache-iceberg-at-adobe-experience-platform-40fa80f8b8de

__Review (1-2 sentences):__ Great practical article about migration from HDFS to Iceberg. Motivation, different migration strategies and its choice, lessons learnt.

**Comment by Ceridan** [comment]
Published in Digest [#8](https://digest.deordie.org/08_4_things_and_5_more_reasons/).
