### ISSUE TITLE
Data Mesh Principle / Zhamak Dehghani 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#48]
__URL:__
https://martinfowler.com/articles/data-mesh-principles.html

__Review (1-2 sentences):__
This is the next article of Data Mesh idea from founder Zhamak Dehghani. A deeper look at processes and organization around the concept. And we are waiting for  Data Mesh book at the end of the year. You can find the early edition on the O'Reilly platform.

__Link to your profile (GitHub, Twitter, Facebook, etc.) for mention in digest:__

**Comment by Ceridan** [comment]
Published in Digest [#11](https://digest.deordie.org/11_Back_to_school_with_Andy_Pavlo/)
