### ISSUE TITLE
Understanding Kafka partition assignment strategies and how to write your own custom assignor / Florian Hussonnois @ StreamThoughts

### ISSUE THREAD

**Issue by bochkarevnv** [deordie/deordie-digest#49]
__URL:__ https://medium.com/streamthoughts/understanding-kafka-partition-assignment-strategies-and-how-to-write-your-own-custom-assignor-ebeda1fc06f3

__Review (1-2 sentences):__ Continuation of the article from Digest 7. The author goes deeper into the work of consumer groups and the assignment of partitions.

**Comment by Ceridan** [comment]
Published in Digest [#11](https://digest.deordie.org/11_Back_to_school_with_Andy_Pavlo/)
