### ISSUE TITLE
Flink on Kubernetes

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#5]
__URL:__ https://medium.com/empathyco/running-apache-flink-on-kubernetes-10815a26559e

__Review (1-2 sentences):__ In the world where k8s won the race we're trying to run everything on it. Here is the recipe of running Flink on Kubernetes.

**Comment by Ceridan** [comment]
Published in the [Digest #2](https://digest.deordie.org/May_the_Force_be_with_you/).
