### ISSUE TITLE
Higher-Order Functions with Spark 3.1 / David Vrba @ Towards Data Science Blog

### ISSUE THREAD

**Issue by bochkarevnv** [deordie/deordie-digest#50]
__URL:__ https://towardsdatascience.com/higher-order-functions-with-spark-3-1-7c6cf591beaa

__Review (1-2 sentences):__ New functions for manipulating with arrays have been released. Check maybe you can forget about UDF.

__Link to your profile (GitHub, Twitter, Facebook, etc.) for mention in digest:__

**Comment by Ceridan** [comment]
Published in Digest [#9](https://digest.deordie.org/09_Goddess_blessing/).
