### ISSUE TITLE
Hadoop in containers

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#51]
__URL:__ https://eng.uber.com/hadoop-container-blog/

__Review (1-2 sentences):__ testing a product that is oriented at Hadoop infrastructure may be challenging. Here are some insights from Uber on how they containerize Hadoop in their quite complex ecosystem.

**Comment by k-tomak** [comment]
Closed as duplicate  https://github.com/deordie/deordie-digest/issues/40
