### ISSUE TITLE
Distributed Query Engines vs. Data Lake Engines / Patrick Pichler

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#59]
__URL:__ https://medium.com/swlh/the-evolution-of-distributed-sql-based-query-engines-for-big-data-dfcb68102060

__Review (1-2 sentences):__ Will be later

**Comment by Ceridan** [comment]
Published in Digest [#12](https://digest.deordie.org/12_Become_an_open_source_star/)
