### ISSUE TITLE
Selecting datalake storage

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#6]
__URL:__ https://s.asm0dey.ru/Gpp4h

__Review (1-2 sentences):__ Non-immutable formats are the new trend of data storage. Hudi, Iceberg, Delta Lake… which suits your needs better? Check out this article by @lakeFS and choose wisely!

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in Digest [#7](https://digest.deordie.org/07_Late_arriving_digest/).
