### ISSUE TITLE
On Spark, Hive, and Small Files: An In-Depth Look at Spark Partitioning Strategies /  Zachary Ennenga @ Airbnb Engineering Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#60]
__URL:__ https://medium.com/airbnb-engineering/on-spark-hive-and-small-files-an-in-depth-look-at-spark-partitioning-strategies-a9a364f908

__Review (1-2 sentences):__ Millions of small files in HDFS or almost all you want to know about spark partitioning. At least for a start :)

**Comment by Ceridan** [comment]
Published in Digest [#11](https://digest.deordie.org/11_Back_to_school_with_Andy_Pavlo/)
