### ISSUE TITLE
How Airbnb Enables Consistent Data Consumption at Scale / Airbnb Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#61]
__URL:__ https://medium.com/airbnb-engineering/how-airbnb-enables-consistent-data-consumption-at-scale-1c0b6a8b9206

__Review (1-2 sentences):__ Airbnb metrics series coming back! Here we can find out how and why they built API layer over metrics and dimensions. And how it was integrated into BI and reporting tools.

**Comment by Ceridan** [comment]
Published in Digest [#12](https://digest.deordie.org/12_Become_an_open_source_star/)
