### ISSUE TITLE
Why you should try something else than Airflow for data pipeline orchestration / Mehdi Ouazza 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#62]
__URL:__ https://towardsdatascience.com/why-you-should-try-something-else-than-airflow-for-data-pipeline-orchestration-7a0a2c91c341

__Review (1-2 sentences):__ Now the article's name speaks for itself :)

**Comment by Ceridan** [comment]
Published in Digest [#12](https://digest.deordie.org/12_Become_an_open_source_star/)
