### ISSUE TITLE
Success at Apache: from Mentee to PMC /  Ephraim Anierobi @ Apache Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#64]
__URL:__ https://blogs.apache.org/foundation/entry/success-at-apache-from-mentee

__Review (1-2 sentences):__ May be it's time to become an open source star! Inspire and Just start to commit into Apache products :)

**Comment by Ceridan** [comment]
Published in Digest [#12](https://digest.deordie.org/12_Become_an_open_source_star/)
