### ISSUE TITLE
Streaming 101: The world beyond batch / Tyler Akidau 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#66]
__URL:__
Part I: https://www.oreilly.com/radar/the-world-beyond-batch-streaming-101/
Part II: https://www.oreilly.com/radar/the-world-beyond-batch-streaming-102/

__Review (1-2 sentences):__
Here are two very fundamental articles that help you to go deeper into streaming theory and understand the key difference between batch and stream processing in terms of time. Help you collect correct questions that you should ask yourself when you work with watermarks, triggers, and windows.

These articles have changed my understanding forever and I hope will change yours

**Comment by Ceridan** [comment]
Published in Digest [#12](https://digest.deordie.org/12_Become_an_open_source_star/)
