### ISSUE TITLE
Why Python is Slow: Looking Under the Hood / Jake VanderPlas @ Pythonic Perambulations blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#69]
__URL:__ http://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

__Review (1-2 sentences):__ Indeed, why? Great article by the multiple python books author.

**Comment by Ceridan** [comment]
Published in Digest [#13](https://digest.deordie.org/13_Snake_menace/)
