### ISSUE TITLE
Data Analytics with SQLite

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#7]
__URL:__ https://s.asm0dey.ru/gs7NP

__Review (1-2 sentences):__ Did you know you can explore CSV with SQLite? Load JSONs and CSVs, call analytical functions and even define UDFs? It's real analytical engine, not a toy DB.

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in Digest [#5](https://digest.deordie.org/05_Big_data_with_a_toy_database/).
