### ISSUE TITLE
Python Performance Tuning: 20 Simple Tips / Kevin Cunningham @ Stackify Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#70]
__URL:__ https://stackify.com/20-simple-python-performance-tuning-tips/amp/

__Review (1-2 sentences):__ What do we love more than performance tuning? I don't know.

**Comment by Ceridan** [comment]
Published in Digest [#13](https://digest.deordie.org/13_Snake_menace/)
