### ISSUE TITLE
The Future of the Data Engineer / Barr Moses @ Towards Data Science Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#72]
__URL:__ https://towardsdatascience.com/the-future-of-the-data-engineer-4dcfa53800ab

__Review (1-2 sentences):__ *Feels like a bit of a heart-to-heart. Do you (data engineer) feel yourself as worst seat at the table?*

**Comment by Ceridan** [comment]
Published in Digest [#14](https://digest.deordie.org/14_NullPointerException/)
