### ISSUE TITLE
Introducing Amazon S3 shuffle in AWS Glue / AWS Big Data Blog  

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#74]
__URL:__ https://aws.amazon.com/blogs/big-data/introducing-amazon-s3-shuffle-in-aws-glue/

__Review (1-2 sentences):__ Good explanations of how shuffle works, how it uses local disks, how to track it in AWS Glue UI, what problems we can potentially have and how to escape it.

**Comment by Ceridan** [comment]
Published in Digest [#14](https://digest.deordie.org/14_NullPointerException/)
