### ISSUE TITLE
Landing data on S3: the good, the bad, and the ugly -  Sergey Ivanychev @Joom Blog at Medium

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#75]
__URL:__ https://medium.com/joom/landing-data-on-s3-the-good-the-bad-and-the-ugly-ca42a1d4408d

__Review (1-2 sentences):__ The good, the bad, and the ugly about how to consume events from Kafka into Data Platform.

**Comment by Ceridan** [comment]
Published in Digest [#15](https://digest.deordie.org/15_The_good_the_bad_the_ugly_and_AWS/)
