### ISSUE TITLE
The physical structure of an SQL index - Kelvin Gakuo @ Medium

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#76]
__URL:__ https://medium.com/@kelvingakuo/the-physical-structure-of-an-sql-index-a246a4c8b2b5

__Review (1-2 sentences):__ Good article to brush up your knowledge about indexes before interview.

**Comment by Ceridan** [comment]
Published in Digest [#15](https://digest.deordie.org/15_The_good_the_bad_the_ugly_and_AWS/)
