### ISSUE TITLE
How the Modern Data Stack is Reshaping Data Engineering - Max Beauchemin @ Preset Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#77]
__URL:__ https://preset.io/blog/reshaping-data-engineering/

__Review (1-2 sentences):__ One of the first data engineers at Facebook and Airbnb, he wrote and open sourced the wildly popular orchestrator, Apache Airflow, followed shortly thereafter by Apache Superset, a data exploration tool that’s taking the data viz landscape by storm. Currently, Max is CEO and co-founder of Preset. His article worth to be red. Do you still have doubts?

**Comment by Ceridan** [comment]
Published in Digest [#15](https://digest.deordie.org/15_The_good_the_bad_the_ugly_and_AWS/)
