### ISSUE TITLE
How to Build Your Data Reliability Stack - Barr Moses @ Towards Data Science Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#78]
__URL:__ https://towardsdatascience.com/how-to-build-your-data-reliability-stack-7cf1a0f5bf30

__Review (1-2 sentences):__ What do you need to not to worry about your data

**Comment by Ceridan** [comment]
Published in Digest [#15](https://digest.deordie.org/15_The_good_the_bad_the_ugly_and_AWS/)
