### ISSUE TITLE
Announcing Amazon EMR Serverless (Preview): Run big data applications without managing servers - AWS Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#79]
__URL:__ https://aws.amazon.com/blogs/big-data/announcing-amazon-emr-serverless-preview-run-big-data-applications-without-managing-servers/

__Review (1-2 sentences):__ EMR Serverless in public preview!

**Comment by Ceridan** [comment]
Published in Digest [#15](https://digest.deordie.org/15_The_good_the_bad_the_ugly_and_AWS/)
