### ISSUE TITLE
Root Cause Analysis for Data Engineers

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#8]
__URL:__ https://towardsdatascience.com/root-cause-analysis-for-data-engineers-782c02351697

__Review (1-2 sentences):__ post on how to perform data downtime analysis: where should we look,  and quite controversial idea on "in whch order" we should look at potential causes

**Comment by Ceridan** [comment]
Published in the [Digest #2](https://digest.deordie.org/May_the_Force_be_with_you/).
