### ISSUE TITLE
HelloFresh Journey to the Data Mesh - HelloFresh Blog

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#80]
__URL:__
https://engineering.hellofresh.com/hellofresh-journey-to-the-data-mesh-7fe590f26bda

__Review (1-2 sentences):__ To read other people's stories is interesting because it might look like yours.

**Comment by Ceridan** [comment]
Published in Digest [#16](https://digest.deordie.org/16_We_wish_you_a_Merry_Christmas_Exactly_Once/).
