### ISSUE TITLE
Building data platform in PySpark. Part 1. Python and Scala interop - Sergey Ivanychev @ Joom Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#82]
__URL:__ https://medium.com/joom/building-data-platform-in-pyspark-part-1-python-and-scala-interop-c52f96b7dc59

__Review (1-2 sentences):__

**Comment by Ceridan** [comment]
Published in Digest [#16](https://digest.deordie.org/16_We_wish_you_a_Merry_Christmas_Exactly_Once/).
