### ISSUE TITLE
What does in-sync in apache kafka really mean / Lovisa Johansson

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#83]
__URL:__
https://www.cloudkarafka.com/blog/what-does-in-sync-in-apache-kafka-really-mean.html

__Review (1-2 sentences):__
A little article for better understanding the separation line between producer and consumer guarantee. It's also useful for a better understanding of how exactly one guarantee can be rich and which cost does it has.

**Comment by Ceridan** [comment]
Published in Digest [#17](https://digest.deordie.org/17_Pasha_discovers_dbt/).
