### ISSUE TITLE
Exactly-Once Semantics Are Possible: Here’s How Kafka Does It / Confluent 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#84]
__URL:__
https://www.confluent.io/blog/exactly-once-semantics-are-possible-heres-how-apache-kafka-does-it/
https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging

__Review (1-2 sentences):__
This is a very interesting explanation about reaching exactly-once semantics. These are just two simple words but this is very not trivial. You should keep in mind a lot of different things and consider different failure scenarios. I think this understanding can help you when you design your pipelines.

**Comment by Ceridan** [comment]
Published in Digest [#16](https://digest.deordie.org/16_We_wish_you_a_Merry_Christmas_Exactly_Once/).
