### ISSUE TITLE
Data Lineage with OpenLineage and Airflow -  Astronomer

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#85]
__URL:__ https://www.youtube.com/watch?v=2s013GQy1Sw

__Review (1-2 sentences):__ Beneficial webinar about how to implement data lineage with Marquez and Airflow. With real examples, not only theory!

**Comment by Ceridan** [comment]
Published in Digest [#16](https://digest.deordie.org/16_We_wish_you_a_Merry_Christmas_Exactly_Once/).
