### ISSUE TITLE
A brief history of the metrics store - Towards Data Science Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#86]
__URL:__ https://towardsdatascience.com/a-brief-history-of-the-metrics-store-28208ec8f6f1

__Review (1-2 sentences):__ We haven't learned about feature store yet. But it won't stop us to read about Metric stores :)

**Comment by Ceridan** [comment]
Published in Digest [#16](https://digest.deordie.org/16_We_wish_you_a_Merry_Christmas_Exactly_Once/).
