### ISSUE TITLE
Apache Spark Performance Boosting - Halil Ertan @ Towards Data Science

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#87]
__URL:__ https://towardsdatascience.com/apache-spark-performance-boosting-e072a3ec1179

__Review (1-2 sentences):__ We understand, that it's just a few hacks about Spark optimizations, but it's a nice way to start.

**Comment by Ceridan** [comment]
Published in Digest [#17](https://digest.deordie.org/17_Pasha_discovers_dbt/).
