### ISSUE TITLE
7 Must-Know Data Buzzwords in 2022 /  Coco Li @ Medium

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#88]
__URL:__ https://medium.com/kyligence/7-must-know-data-buzzwords-in-2022-9d3d977a43f4

__Review (1-2 sentences):__ Just check your knowledge!

**Comment by Ceridan** [comment]
Published in Digest [#17](https://digest.deordie.org/17_Pasha_discovers_dbt/).
