### ISSUE TITLE
How I started out with dbt / Pasha Finkelshteyn @ JetBrains Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#89]
__URL:__ https://blog.jetbrains.com/big-data-tools/2022/01/25/how-i-started-out-with-dbt/

__Review (1-2 sentences):__ If you ever wanted to try DBT you can do it with Pasha. Many pictures and code snippets were added for free :)

**Comment by Ceridan** [comment]
Published in Digest [#17](https://digest.deordie.org/17_Pasha_discovers_dbt/).
