### ISSUE TITLE
MLOps best practices

### ISSUE THREAD

**Issue by asm0dey** [deordie/deordie-digest#9]
__URL:__ https://towardsdatascience.com/mlops-practices-for-data-scientists-dbb01be45dd8

__Review (1-2 sentences):__ quite extensive description of common pitfalls, which ml engineer may observe in process of ml products delivery in conjunction with best practices description.

_Do not forget to add labels._

**Comment by Ceridan** [comment]
Published in the [Digest #1](https://digest.deordie.org/Pilot/)
