### ISSUE TITLE
Anna Concurrenina by Kyle Kingsbury

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#92]
__URL:__
https://youtu.be/eSaFVX4izsQ

__Review (1-2 sentences):__
I think Kyle Kingsbury is a very familiar person by his project [jepsen](https://jepsen.io/consistency). (If don't familiar with it you should go to it right now :)). In this talk, Kyle told about databases lies. 

Almost all databases claim the consistency model but this model is usually with holes. It is very interesting to know exactly which hole was in which databases.

**Comment by Ceridan** [comment]
@DashaBulanova, it is worth being added to the first position just because of the title. It is legendary!

**Comment by Ceridan** [comment]
Published in Digest [#18](https://digest.deordie.org/18_Consistency_fundamentals_by_Leo_Tolstoy/).
