### ISSUE TITLE
What Every Programmer has to know about Database Storage by Alex Petrov

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#93]
__URL:__
https://youtu.be/e1wbQPbFZdk

__Review (1-2 sentences):__
In the world of Big Data, it’s important to know how the Database Storage works in order to be able to pick a right tool right job. The talk covers evaluation techniques, to choose storage with best read, write or memory overhead, best suitable for your data.

This information will help you to navigate the world of databases and stream processing engines, each of which uses a specific storage type or offers multiple different possibilities. You will gain understanding the trade-offs different Storage types bring as you scale out your data and plan for growth.

Alex Petrov is a Database and Storage Systems enthusiast, Apache Cassandra committer. He's been working on data processing pipelines and near-real-time backends for a better part of a decade.

**Comment by Ceridan** [comment]
Published in Digest [#18](https://digest.deordie.org/18_Consistency_fundamentals_by_Leo_Tolstoy/).
