### ISSUE TITLE
Watermarks in Stream Processing Systems: Semantics and Comparative Analysis of Apache Flink and Google Cloud Dataflow / Tyler Akidau  

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#94]
__URL:__
https://vldb.org/pvldb/vol14/p3135-begoli.pdf

__Review (1-2 sentences):__
A new white paper from Tyler Akidau (author of the very cool book "Streaming Systems") where they compare watermarks in different aspects in d Google Cloud Dataflow and Apache Flink. Even if you don't work with I think this white paper deserves your time. 
Watermarks represent the temporal completeness of an out-of-order data stream. Reasoning about the completeness of infinite streams is one of the most critical challenges faced by stream processing systems. It’s also one of the least understood and least adequately addressed compared to other approaches for dealing with the completeness of unbounded data streams.

**Comment by Ceridan** [comment]
Published in Digest [#19](https://digest.deordie.org/19_Back_to_business/).
