### ISSUE TITLE
Stop Treating Your Data Engineer Like a Data Catalog /  Barr Moses @ Medium 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#95]
__URL:__ https://barrmoses.medium.com/stop-treating-your-data-engineer-like-a-data-catalog-14ed3eacf646

__Review (1-2 sentences):__ Data engineers are not data catalogs! That says it all. There is a small guide on how to make dream come true.

**Comment by Ceridan** [comment]
Published in Digest [#18](https://digest.deordie.org/18_Consistency_fundamentals_by_Leo_Tolstoy/).
