### ISSUE TITLE
Designing Instagram / HighScalability Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#96]
__URL:__ http://highscalability.com/blog/2022/1/11/designing-instagram.html

__Review (1-2 sentences):__ Do you want to try to design Instagram with Machine Learning Lead from Amazon? Well, now you can do it.

**Comment by Ceridan** [comment]
Published in Digest [#19](https://digest.deordie.org/19_Back_to_business/).
