### ISSUE TITLE
Powering real-time data analytics with Druid at Twitter / Twitter Engineering Blog 

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#97]
__URL:__ https://blog.twitter.com/engineering/en_us/topics/infrastructure/2022/powering-real-time-data-analytics-with-druid-at-twitter

__Review (1-2 sentences):__ At least, now I know that Druid has out-of-the-box ingestion connectors for Apache Kafka, and it seems that it works great! Just check Twitter streaming architecture.

**Comment by Ceridan** [comment]
Published in Digest [#19](https://digest.deordie.org/19_Back_to_business/).
