### ISSUE TITLE
Presto on Apache Kafka At Uber Scale / User Engineering Blog

### ISSUE THREAD

**Issue by k-tomak** [deordie/deordie-digest#98]
__URL:__ https://eng.uber.com/presto-on-apache-kafka-at-uber-scale/

__Review (1-2 sentences):__ I like Uber engineering posts so much. Because they seem like ADRs: problem, current environment description, alternatives, supposed architecture.

**Comment by Ceridan** [comment]
Published in Digest [#19](https://digest.deordie.org/19_Back_to_business/).
