### ISSUE TITLE
Real-Time Supply Chain with Apache Kafka in the Food and Retail Industry / Walmart 

### ISSUE THREAD

**Issue by DashaBulanova** [deordie/deordie-digest#99]
__URL:__
https://www.kai-waehner.de/blog/2022/02/25/real-time-supply-chain-with-apache-kafka-in-food-retail-industry/

__Review (1-2 sentences):__
I see a lot of discussions around the topic do you really need streaming data? Here is a real-world example from one of the biggest retailers of how to use and why to use real-time data streaming. This article is more an overview one a technical one. Just for taking a look at use cases where they adopted it.

**Comment by Ceridan** [comment]
Published in Digest [#20](https://digest.deordie.org/20_Fantastic_Beasts_And_Where_To_Find_Them/).
